nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.6.0.cjs

# private packages from @leaguetavern / @hanxven
# requires a valid GitHub PAT set to NODE_AUTH_TOKEN environment variable
npmScopes:
  leaguetavern:
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmAuthToken: '${NODE_AUTH_TOKEN}'
  hanxven:
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmAuthToken: '${NODE_AUTH_TOKEN}'
