nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.6.0.cjs

# private packages from @leaguetavern
# requires a valid GitHub PAT set to NODE_AUTH_TOKEN environment variable with repo and write:packages scopes
npmScopes:
  leaguetavern:
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmAuthToken: '${NODE_AUTH_TOKEN}'
